# Generated by Django 2.0 on 2019-04-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='thunmnail',
            new_name='thumbnail',
        ),
    ]
